### ISSUE TITLE
Collection Backend

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geocore#3]
Collection Backend for Parent / Child relationship

**Comment by indiciumx** [comment]
@bo-lu is this in a cloud formation and ready for release to dev/staging?

**Comment by bo-lu** [comment]
@indiciumx  Yes, it is ready. Should I run it on staging?

**Comment by bo-lu** [comment]
I will push to staging and prod this week.

Mockup for records that are part of a collection (i.e., [085024ac-5a48-427a-a2ea-d62af73f2142](https://geocore-dev.api.geo.ca/collections?id=085024ac-5a48-427a-a2ea-d62af73f2142)):
![mockup-parent-child](https://user-images.githubusercontent.com/18405829/200422689-fc643007-d68d-4b07-b29a-f6efe0d9b351.png)

Sample API call:
![collections-api](https://user-images.githubusercontent.com/18405829/200423625-b00cb483-6951-435f-9bf8-812684105d9a.PNG)

Note:
- Do not display 'Related Products' if both the 'parent' and 'sibling' in the API are both null.
- When a record is the parent (parent is null, siblings is not null), every item in the table should have TYPE 'Member'.
- When a record is a child record, (parent is not null, siblings is not null) it should list it's parent with TYPE 'Parent' and list it's siblings as TYPE 'Member'.

**Comment by bo-lu** [comment]
API is ready on staging:
https://geocore-stage.api.geo.ca/collections?id=26c57e53-2646-491b-b385-5813b23d8a96

Notes: 
- update the geocore-transformation lambda to the latest version
- run the CloudFormation to deploy the geocore-collections lambda
- reharvest all records to populate the 'parentIdentifier' field

**Comment by bo-lu** [comment]
Pushed to stage: https://app-stage.geo.ca/result?id=085024ac-5a48-427a-a2ea-d62af73f2142&lang=en

**Comment by bo-lu** [comment]
Pushed to prod: https://app.geo.ca/result?id=085024ac-5a48-427a-a2ea-d62af73f2142&lang=en
