### ISSUE TITLE
Popup or message when 'add to map' is greyed out

### ISSUE THREAD

**Issue by bo-lu** [Canadian-Geospatial-Platform/geocore#38]
**Describe the bug**
When 'Add to Map' and 'Add to MyMap' is greyed out, we need to a pop up or message when a user tries to click it. 

The message can be: 
English: "This record has no viewable component."
French: "Cet enregistrement n'a pas d'élément visible."

**To Reproduce**
Example record:
https://app.geo.ca/result?id=085024ac-5a48-427a-a2ea-d62af73f2142&lang=en

**Expected behavior**
A popup or message when I click the greyed out 'Add to Map' and 'Add to MyMap' buttons.

**Comment by bo-lu** [comment]
Pushed to stage: https://app-stage.geo.ca/result?id=085024ac-5a48-427a-a2ea-d62af73f2142&lang=en

**Comment by sean-eagles** [comment]
Title should be changed to Not Viewable instead of No Viewable.

**Comment by bo-lu** [comment]
Changed to "No viewable content" and "Pas de contenu visible". 

https://app.geo.ca/result?id=085024ac-5a48-427a-a2ea-d62af73f2142&lang=en

**Comment by jvanulde** [comment]
Pushed to PROD and functioning.

<img width="1346" alt="Screen Shot 2022-11-15 at 2 22 37 PM" src="https://user-images.githubusercontent.com/2255248/202037497-f560fecb-e442-498f-8f9c-9d01e12b884f.png">
