### ISSUE TITLE
Convert markdown in record description to HTML

### ISSUE THREAD

**Issue by bo-lu** [Canadian-Geospatial-Platform/geocore#39]
**Describe the bug**
For some records that have imbedded markdown, it would be best to convert them to HTML
Example: https://app.geo.ca/result?id=11990a35-912e-4002-b197-d57dd88836d7&lang=en

**To Reproduce**
Under "ABOUT THIS DATASET" in: https://app.geo.ca/result?id=11990a35-912e-4002-b197-d57dd88836d7&lang=en

**Expected behavior**
A bullet and hyperlink. For example, how the Open Canada portal handles it: https://open.canada.ca/data/en/dataset/11990a35-912e-4002-b197-d57dd88836d7

**Comment by jvanulde** [comment]
@dennisfu @bo-lu is this deployed on DEV now?

**Comment by dennisfu** [comment]
Hi @bo-lu the urls are from the description text, seems we are going to add link to the url, then how can we get the links url from the pure text? does these links always have the same format ? now I can see like this:  -[title] (url link)
and are the url all have the same domain and path https://open.canada.ca/data/en/dataset/ ?

Please clearify

**Comment by bo-lu** [comment]
Hi Dennis,

For now, lets just convert the simple case of a fully fledged link. So lets match the format `[XYZ](https://XYZ)` 

E.g. `[Text for link](https://google.com)` would appear as [Text for link](https://google.com) on the metadata details page.

**Comment by bo-lu** [comment]
Maybe we can parse bold text as well? This record has bold text:

https://app.geo.ca/result?id=08b810c2-7c81-40f1-adb1-c32c8a2c9f50&lang=en

With the markdown `**TEXT**`

**Comment by bo-lu** [comment]
https://app-stage.geo.ca/result?id=08b810c2-7c81-40f1-adb1-c32c8a2c9f50&lang=en

**Comment by bo-lu** [comment]
Pushed to prod: https://app.geo.ca/result?id=08b810c2-7c81-40f1-adb1-c32c8a2c9f50&lang=en
