### ISSUE TITLE
Add Saved Search Button

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geocore#55]
If a user is logged in, when they search add a button next to the keyword only button to save the search on both the map search and keyword search only screens. This button will post to the /saved_search/add endpoint with the appropriate information and userId. 

![Screenshot_20230208_110411](https://user-images.githubusercontent.com/16785514/217585695-059c8f2e-aa64-472e-9041-a7005e3b823f.png)

**Comment by raviinder** [comment]
@indiciumx  can you please provide Mockup for same.

**Comment by indiciumx** [comment]
Duplicate of https://github.com/Canadian-Geospatial-Platform/app.geo.ca/issues/8

**Comment by indiciumx** [comment]
Duplicate of https://github.com/Canadian-Geospatial-Platform/app.geo.ca/issues/7
