### ISSUE TITLE
Additional sort filters are needed (e.g. popularity, most recent, title, relevance)

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geocore#8]
Popularity[¶](https://redmine.gcgeo.gc.ca/redmine/issues/28050#Popularity)
This work is complete and popularity data is appended to the parquet file when the lambda is run.

Most recent
This should be the 'lastApprovalTime' from [#24992](https://redmine.gcgeo.gc.ca/redmine/issues/24992). However, it does not appear to be exposed in the Lucene index. Example: [85d6c4c2-6683-4d56-adf4-8cacef2676be](https://maps.canada.ca/geonetwork/srv/eng/q?fast=index&buildSummary=false&uuid=85d6c4c2-6683-4d56-adf4-8cacef2676be)

Instead, we can use the change api, but it has to be paginated as the change API supports up to 4000 records.

To be documented in: https://redmine.gcgeo.gc.ca/redmine/projects/geo-ca/wiki/Search_filter_API_(popularity_most_recent)

Title
This can be handled by Athena

Relevance
Similarity engine being developed in [#28055](https://redmine.gcgeo.gc.ca/redmine/issues/28055)

Documentation to be populated in: https://redmine.gcgeo.gc.ca/redmine/projects/geo-ca/wiki/Similarity_engine_API

**Comment by bo-lu** [comment]
Here is a mockup of what we are working toward:

The first filter we will be working toward is the "most recent". I hope to have that ready in a couple of days

![image.png](https://images.zenhubusercontent.com/636ac9dd42f1dc0b18a54293/c59e384f-ff2b-4ec1-ada3-499c967fd556)

**Comment by xinli-cai** [comment]
Hey @bo-lu, The mock up looks good. A quick suggestion, is it possible to add search filter 'metadata standards' to allow user choose search results for records following HNAP, STAC, DCat, Dublin core, ISO down the road? This could help to address the concerns about STAC is not HNAP compliant.

**Comment by johnweng001** [comment]
@bo-lu  I registered an account for accessing https://redmine.gcgeo.gc.ca/redmine/projects/geo-ca/wiki/Similarity_engine_API
It is pending admin approval.

**Comment by elatsis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geocore/8?planning-poker) with Zenhub @bo-lu @johnweng001

**Comment by jvanulde** [comment]
@bo-lu, @xinli-cai is this supposed to be closed? I don't think the relevance sorting was ever implemented.

**Comment by xinli-cai** [comment]
We have not yet implemented the relevance sorting feature. I suggest we close this issue and open a separate one dedicated to 'sort by relevance'. The work on the Similarity Engine is distinct from relevance sorting. To implement relevance sorting, we'll need to address several aspects such as designing the ML algorithm, performing textual analysis, indexing, and gathering feedback. While we are not currently working on relevance sorting,  it will be addressed within the scope of the semantic search engine.
